// projects/dumbql/core/src/lib/skeleton.component.ts
import { Component, input } from '@angular/core';

export type SkeletonVariant = 'text' | 'circle' | 'rect' | 'card' | 'table' | 'list' | 'paragraph';
export type SkeletonAnimation = 'pulse' | 'wave' | 'none';

@Component({
	selector: 'dumbql-skeleton',
	standalone: true,
	templateUrl: './skeleton.component.html',
	styleUrl: './skeleton.component.scss',
})
export class DumbqlSkeletonComponent {
	readonly variant = input<SkeletonVariant>('text');
	readonly animation = input<SkeletonAnimation>('pulse');
	readonly width = input<string>();
	readonly height = input<string>();
	readonly textWidth = input<string>('100%');
	readonly tableRows = input(5);
	readonly listItems = input(4);
	readonly paragraphLines = input(4);
	readonly ariaLabel = input('Loading content');
}

<div
	class="dumbql-skeleton dumbql-skeleton-{{ variant() }} dumbql-skeleton-{{ animation() }}"
	[style.width]="width()"
	[style.height]="height()"
	[attr.aria-label]="ariaLabel()"
	role="status"
>
	@switch (variant()) {
		@case ('text') {
			<div class="dumbql-skeleton-line" [style.width]="textWidth()"></div>
		}
		@case ('circle') {
			<div class="dumbql-skeleton-circle"></div>
		}
		@case ('rect') {
			<div class="dumbql-skeleton-rect"></div>
		}
		@case ('card') {
			<div class="dumbql-skeleton-card">
				<div class="dumbql-skeleton-card-img"></div>
				<div class="dumbql-skeleton-card-body">
					<div class="dumbql-skeleton-line dumbql-skeleton-line-title"></div>
					<div class="dumbql-skeleton-line"></div>
					<div class="dumbql-skeleton-line dumbql-skeleton-line-short"></div>
				</div>
			</div>
		}
		@case ('table') {
			<div class="dumbql-skeleton-table">
				@for (row of tableRows(); track row) {
					<div class="dumbql-skeleton-table-row">
						<div class="dumbql-skeleton-table-cell"></div>
						<div class="dumbql-skeleton-table-cell"></div>
						<div class="dumbql-skeleton-table-cell"></div>
					</div>
				}
			</div>
		}
		@case ('list') {
			<div class="dumbql-skeleton-list">
				@for (item of listItems(); track item) {
					<div class="dumbql-skeleton-list-item">
						<div class="dumbql-skeleton-circle dumbql-skeleton-circle-sm"></div>
						<div class="dumbql-skeleton-list-text">
							<div class="dumbql-skeleton-line dumbql-skeleton-line-title"></div>
							<div class="dumbql-skeleton-line dumbql-skeleton-line-short"></div>
						</div>
					</div>
				}
			</div>
		}
		@case ('paragraph') {
			<div class="dumbql-skeleton-paragraph">
				@for (line of paragraphLines(); track line) {
					<div class="dumbql-skeleton-line" [style.width]="line === paragraphLines() ? '60%' : '100%'"></div>
				}
			</div>
		}
	}
</div>

// projects/dumbql/react/src/lib/skeleton.tsx
import { type CSSProperties, type ReactNode } from 'react';

export type SkeletonVariant = 'text' | 'circle' | 'rect' | 'card' | 'table' | 'list' | 'paragraph';
export type SkeletonAnimation = 'pulse' | 'wave' | 'none';

export interface SkeletonProps {
	readonly variant?: SkeletonVariant;
	readonly animation?: SkeletonAnimation;
	readonly width?: string | number;
	readonly height?: string | number;
	readonly textWidth?: string;
	readonly tableRows?: number;
	readonly listItems?: number;
	readonly paragraphLines?: number;
	readonly style?: CSSProperties;
	readonly className?: string;
}

const animStyle: Record<SkeletonAnimation, CSSProperties> = {
	pulse: { animation: 'dumbql-pulse 1.8s cubic-bezier(0.4,0,0.6,1) infinite' },
	wave: { animation: 'dumbql-wave 1.6s ease-in-out infinite', background: 'linear-gradient(90deg, var(--dumbql-skeleton-bg,#e2e8f0) 25%, var(--dumbql-skeleton-shine,#f1f5f9) 50%, var(--dumbql-skeleton-bg,#e2e8f0) 75%)', backgroundSize: '200% 100%' },
	none: {},
};

const baseLine = (w = '100%'): CSSProperties => ({
	height: 14, borderRadius: 4, width: w, background: 'var(--dumbql-skeleton-bg, #e2e8f0)',
});

function SkeletonLine({ w, anim }: { readonly w?: string; readonly anim: SkeletonAnimation }) {
	return <div style={{ ...baseLine(w), ...animStyle[anim] }} />;
}

function SkeletonCard({ anim }: { readonly anim: SkeletonAnimation }) {
	return (
		<div style={{ border: '1px solid var(--dumbql-skeleton-border, #e2e8f0)', borderRadius: 8, overflow: 'hidden' }}>
			<div style={{ width: '100%', height: 160, background: 'var(--dumbql-skeleton-bg, #e2e8f0)', ...animStyle[anim] }} />
			<div style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 10 }}>
				<SkeletonLine w="70%" anim={anim} />
				<SkeletonLine anim={anim} />
				<SkeletonLine w="50%" anim={anim} />
			</div>
		</div>
	);
}

function SkeletonTable({ rows, anim }: { readonly rows: number; readonly anim: SkeletonAnimation }) {
	return (
		<div style={{ width: '100%' }}>
			{Array.from({ length: rows }, (_, i) => (
				<div key={i} style={{ display: 'flex', gap: 12, padding: '12px 0', borderBottom: '1px solid var(--dumbql-skeleton-border, #e2e8f0)' }}>
					<div style={{ flex: 1, height: 16, borderRadius: 4, background: 'var(--dumbql-skeleton-bg, #e2e8f0)', ...animStyle[anim] }} />
					<div style={{ flex: 1, height: 16, borderRadius: 4, background: 'var(--dumbql-skeleton-bg, #e2e8f0)', ...animStyle[anim] }} />
					<div style={{ flex: 0.5, height: 16, borderRadius: 4, background: 'var(--dumbql-skeleton-bg, #e2e8f0)', ...animStyle[anim] }} />
				</div>
			))}
		</div>
	);
}

function SkeletonList({ items, anim }: { readonly items: number; readonly anim: SkeletonAnimation }) {
	return (
		<div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
			{Array.from({ length: items }, (_, i) => (
				<div key={i} style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
					<div style={{ width: 32, height: 32, borderRadius: '50%', background: 'var(--dumbql-skeleton-bg, #e2e8f0)', ...animStyle[anim] }} />
					<div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 8 }}>
						<SkeletonLine w="70%" anim={anim} />
						<SkeletonLine w="50%" anim={anim} />
					</div>
				</div>
			))}
		</div>
	);
}

function SkeletonParagraph({ lines, anim }: { readonly lines: number; readonly anim: SkeletonAnimation }) {
	return (
		<div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
			{Array.from({ length: lines }, (_, i) => (
				<SkeletonLine key={i} w={i === lines - 1 ? '60%' : '100%'} anim={anim} />
			))}
		</div>
	);
}

export function Skeleton({
	variant = 'text', animation = 'pulse', width, height, textWidth = '100%',
	tableRows = 5, listItems = 4, paragraphLines = 4, style, className = '',
}: SkeletonProps): ReactNode {
	const wrap: CSSProperties = { borderRadius: 4, overflow: 'hidden', width: width as string | undefined, height: height as string | undefined, ...style };

	const content = (() => {
		switch (variant) {
		case 'text': return <SkeletonLine w={textWidth} anim={animation} />;
		case 'circle': return <div style={{ width: 48, height: 48, borderRadius: '50%', background: 'var(--dumbql-skeleton-bg, #e2e8f0)', ...animStyle[animation] }} />;
		case 'rect': return <div style={{ width: '100%', height: 120, borderRadius: 4, background: 'var(--dumbql-skeleton-bg, #e2e8f0)', ...animStyle[animation] }} />;
		case 'card': return <SkeletonCard anim={animation} />;
		case 'table': return <SkeletonTable rows={tableRows} anim={animation} />;
		case 'list': return <SkeletonList items={listItems} anim={animation} />;
		case 'paragraph': return <SkeletonParagraph lines={paragraphLines} anim={animation} />;
		}
	})();

	return (
		<div className={`dumbql-skeleton ${className}`.trim()} style={wrap} role="status" aria-label="Loading content">
			{content}
			<style>{`
				@keyframes dumbql-pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }
				@keyframes dumbql-wave { 0% { background-position: 200% 0; } 100% { background-position: -200% 0; } }
			`}</style>
		</div>
	);
}
