// demos/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { gql } from '@dumbql/client';
import { DumbqlQuery } from '@dumbql/core';

const GET_NOTES = gql`
  query {
    getNotes {
      id
      title
      content
    }
  }
`;

interface Note {
  id: string;
  title: string;
  content: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [DumbqlQuery],
  template: `
    <h1>DumbQL + Angular</h1>

    <ng-template dumbqlQuery [query]="GET_NOTES" let-data let-loading="loading" let-error="error">
      @if (loading) { <p>Loading...</p> }
      @if (error)  { <p>Error: {{ error }}</p> }
      @if (data) {
        <ul>
          @for (note of data.getNotes; track note.id) {
            <li><strong>{{ note.title }}</strong>: {{ note.content }}</li>
          }
        </ul>
      }
    </ng-template>
  `,
})
export class AppComponent {
  readonly GET_NOTES = GET_NOTES;
}

// demos/react/src/App.tsx
import { gql, useQuery } from '@dumbql/react';

const GET_NOTES = gql`
  query {
    getNotes {
      id
      title
      content
    }
  }
`;

export function App() {
  const { data, loading, error } = useQuery(GET_NOTES);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error: {error}</p>;

  return (
    <div>
      <h1>DumbQL + React</h1>
      <ul>
        {data?.getNotes?.map((note: { id: string; title: string; content: string }) => (
          <li key={note.id}><strong>{note.title}</strong>: {note.content}</li>
        ))}
      </ul>
    </div>
  );
}
