// starters/react/src/App.tsx
import { useQuery, gql } from '@dumbql/react';

const GET_NOTES = gql`
  query {
    getNotes {
      id
      title
      content
    }
  }
`;

interface Note {
  id: string;
  title: string;
  content: string;
}

export default function App() {
  const { data, loading, error } = useQuery<{ getNotes: Note[] }>(GET_NOTES);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error: {error}</p>;

  return (
    <div>
      <h1>DumbQL + React</h1>
      <ul>
        {data?.getNotes.map(note => (
          <li key={note.id}>
            <strong>{note.title}</strong>: {note.content}
          </li>
        ))}
      </ul>
    </div>
  );
}

// demos/vue/src/App.vue
<template>
  <div>
    <h1>DumbQL + Vue</h1>
    <p v-if="loading">Loading...</p>
    <p v-else-if="error">Error: {{ error }}</p>
    <ul v-else>
      <li v-for="note in data?.getNotes" :key="note.id">
        <strong>{{ note.title }}</strong>: {{ note.content }}
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { gql, useQuery } from '@dumbql/vue';

const GET_NOTES = gql`
  query {
    getNotes {
      id
      title
      content
    }
  }
`;

const { data, loading, error } = useQuery(GET_NOTES);
</script>
